// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW8LgaWwG0YLykdUAlhd0moiGXwjRLzbs',
    appId: '1:391922944553:web:af3fcc14c03c6f020daa38',
    messagingSenderId: '391922944553',
    projectId: 'starwoke-7318e',
    authDomain: 'starwoke-7318e.firebaseapp.com',
    databaseURL: 'https://starwoke-7318e.firebaseio.com',
    storageBucket: 'starwoke-7318e.appspot.com',
    measurementId: 'G-05V4W5L6DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyMdcpWCi6CETmdL8bwzmPPWVydDQUtys',
    appId: '1:391922944553:android:6eef9a3c8e3c29090daa38',
    messagingSenderId: '391922944553',
    projectId: 'starwoke-7318e',
    databaseURL: 'https://starwoke-7318e.firebaseio.com',
    storageBucket: 'starwoke-7318e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRs_jn-9OYt5LsD4nrS_gkOEt04ZjpV5A',
    appId: '1:391922944553:ios:7aa8ef9bec99bcc90daa38',
    messagingSenderId: '391922944553',
    projectId: 'starwoke-7318e',
    databaseURL: 'https://starwoke-7318e.firebaseio.com',
    storageBucket: 'starwoke-7318e.appspot.com',
    iosClientId: '391922944553-kutilr57ii5t1b82nv1cemcmd7htk7th.apps.googleusercontent.com',
    iosBundleId: 'com.sidox.starwoke',
  );
}
